import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:hotel/model/category_model_local.dart';
import 'package:hotel/model/product_model_local.dart';

class service_controller extends GetxController{
  List<Category_local> fetchCategories(){
    return [
      Category_local(
        id: 1,
        title: "All",
        image: "images/all.png",
      ),
      Category_local(
        id: 2,
        title: "Shoes",
        image: "images/shoes.png",
      ),
      Category_local(
        id: 3,
        title: "Beauty",
        image: "images/beauty.png",
      ),
      Category_local(
        id: 4,
        title: "Jewelry",
        image: "images/jewelry.png",
      ),
      Category_local(
        id: 5,
        title: "Men's Fashion",
        image: "images/men.png",
      ),
      Category_local(
        id: 6,
        title: "Electronics",
        image: "images/men.png",
      ),
      Category_local(
        id: 7,
        title: "Woman's Fashion",
        image: "images/men.png",
      ),
    ];
  }
  List<Product_local> fetchProducts(int categoryId){
    if(categoryId==1){
      return [
        Product_local(
          id: 1,
          title: "Wireless Headphones",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/all/wireless.png",
          price: 120,
          seller: "Tariqul isalm",
          colors: [
            Colors.black,
            Colors.blue,
            Colors.orange,
          ],
          category: 6,
          review: "(320 Reviews)",
          rate: 4.8,
          quantity: 1,
        ),
        Product_local(
          id: 2,
          title: "Woman Sweter",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/all/sweet.png",
          price: 120,
          seller: "Joy Store",
          colors: [
            Colors.brown,
            Colors.deepPurple,
            Colors.pink,
          ],
          category: 7,
          review: "(32 Reviews)",
          rate: 4.5,
          quantity: 1,
        ),
        Product_local(
          id: 3,
          title: "Smart Watch",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/all/miband.jpg",
          price: 55,
          seller: "Ram Das",
          colors: [
            Colors.black,
            Colors.amber,
            Colors.purple,
          ],
          category: 6,
          review: "(20 Reviews)",
          rate: 4.0,
          quantity: 1,
        ),
        Product_local(
          id: 4,
          title: "Mens Jacket",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/all/jacket.png",
          price: 155,
          seller: "Jacket Store",
          colors: [
            Colors.blueAccent,
            Colors.orange,
            Colors.green,
          ],
          category: 5,
          review: "(20 Reviews)",
          rate: 5.0,
          quantity: 1,
        ),
        Product_local(
          id: 5,
          title: "Watch",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/men fashion/watch.png",
          price: 1000,
          seller: "Jacket Store",
          colors: [
            Colors.lightBlue,
            Colors.orange,
            Colors.purple,
          ],
          category: 6,
          review: "(100 Reviews)",
          rate: 5.0,
          quantity: 1,
        ),
        Product_local(
          id: 6,
          title: "Air Jordan",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/shoes/Air Jordan.png",
          price: 255,
          seller: "The Seller",
          colors: [
            Colors.grey,
            Colors.amber,
            Colors.purple,
          ],
          category: 2,
          review: "(55 Reviews)",
          rate: 5.0,
          quantity: 1,
        ),
        Product_local(
          id: 7,
          title: "Super Perfume",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/beauty/perfume.png",
          price: 155,
          seller: "Love Seller",
          colors: [
            Colors.purpleAccent,
            Colors.pinkAccent,
            Colors.green,
          ],
          category: 3,
          review: "(99 Reviews)",
          rate: 4.7,
          quantity: 1,
        ),
        Product_local(
          id: 8,
          title: "Wedding Ring",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/jewelry/wedding ring.png",
          price: 155,
          seller: "I Am Seller",
          colors: [
            Colors.brown,
            Colors.purpleAccent,
            Colors.blueGrey,
          ],
          category: 4,
          review: "(80 Reviews)",
          rate: 4.5,
          quantity: 1,
        ),
        Product_local(
          id:9,
          title: "  Pants",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/women fashion/pants.png",
          price: 155,
          seller: "PK Store",
          colors: [
            Colors.lightGreen,
            Colors.blueGrey,
            Colors.deepPurple,
          ],
          category: 7,
          review: "(55 Reviews)",
          rate: 5.0,
          quantity: 1,
        ),
        Product_local(
          id: 10,
          title: "Air Jordan",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/shoes/Air Jordan.png",
          price: 255,
          seller: "The Seller",
          colors: [
            Colors.grey,
            Colors.amber,
            Colors.purple,
          ],
          category: 2,
          review: "(55 Reviews)",
          rate: 5.0,
          quantity: 1,
        ),
        Product_local(
          id: 11,
          title: "Vans Old Skool",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/shoes/vans old skool.png",
          price: 300,
          seller: "Mrs Store",
          colors: [
            Colors.blueAccent,
            Colors.blueGrey,
            Colors.green,
          ],
          category: 2,
          review: "(200 Reviews)",
          rate: 5.0,
          quantity: 1,
        ),
        Product_local(
          id: 12,
          title: "Women-Shoes",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/shoes/women-shoes.png",
          price: 500,
          seller: "Shoes Store",
          colors: [
            Colors.red,
            Colors.orange,
            Colors.greenAccent,
          ],
          category: 2,
          review: "(100 Reviews)",
          rate: 4.8,
          quantity: 1,
        ),
        Product_local(
          id: 13,
          title: "Sports Shoes",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/shoes/sports shoes.png",
          price: 155,
          seller: "Hari Store",
          colors: [
            Colors.deepPurpleAccent,
            Colors.orange,
            Colors.green,
          ],
          category: 2,
          review: "(60 Reviews)",
          rate: 3.0,
          quantity: 1,
        ),
        Product_local(
          id: 14,
          title: "White Sneaker",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/shoes/white sneaker.png",
          price: 1000,
          seller: "Jacket Store",
          colors: [
            Colors.blueAccent,
            Colors.orange,
            Colors.green,
          ],
          category: 2,
          review: "(00 Reviews)",
          rate: 0.0,
          quantity: 1,
        ),
        Product_local(
          id: 15,
          title: "Face Care Product",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/beauty/face care.png",
          price: 1500,
          seller: "Yojana Seller",
          colors: [
            Colors.pink,
            Colors.amber,
            Colors.deepOrangeAccent,
          ],
          category: 3,
          review: "(200 Reviews)",
          rate: 4.0,
          quantity: 1,
        ),
        Product_local(
          id: 16,
          title: "Super Perfume",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/beauty/perfume.png",
          price: 155,
          seller: "Love Seller",
          colors: [
            Colors.purpleAccent,
            Colors.pinkAccent,
            Colors.green,
          ],
          category: 3,
          review: "(99 Reviews)",
          rate: 4.7,
          quantity: 1,
        ),
        Product_local(
          id: 17,
          title: " Women Kurta",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/women fashion/kurta.png",
          price: 299,
          seller: "Sila Store",
          colors: [
            Colors.grey,
            Colors.black54,
            Colors.purple,
          ],
          category: 7,
          review: "(25 Reviews)",
          rate: 5.0,
          quantity: 1,
        ),
        Product_local(
          id: 18,
          title: "Mens Jacket",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/women fashion/lehenga.png",
          price: 666,
          seller: "My Store",
          colors: [
            Colors.black,
            Colors.orange,
            Colors.green,
          ],
          category: 7,
          review: "(100 Reviews)",
          rate: 4.0,
          quantity: 1,
        ),
        Product_local(
          id: 19,
          title: "T-Shert",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/women fashion/t-shert.png",
          price: 155,
          seller: "Love Store",
          colors: [
            Colors.blueAccent,
            Colors.redAccent,
            Colors.deepOrangeAccent,
          ],
          category: 7,
          review: "(20 Reviews)",
          rate: 5.0,
          quantity: 1,
        ),
        Product_local(
          id: 20,
          title: "  Pants",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/women fashion/pants.png",
          price: 155,
          seller: "PK Store",
          colors: [
            Colors.lightGreen,
            Colors.blueGrey,
            Colors.deepPurple,
          ],
          category: 7,
          review: "(55 Reviews)",
          rate: 5.0,
          quantity: 1,
        ),
        Product_local(
          id: 21,
          title: "Earrings",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/jewelry/earrings.png",
          price: 3000,
          seller: "Gold Store",
          colors: [
            Colors.amber,
            Colors.deepPurple,
            Colors.pink,
          ],
          category: 4,
          review: "(320 Reviews)",
          rate: 4.5,
          quantity: 1,
        ),
        Product_local(
          id: 22,
          title: "Jewelry-Box",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/jewelry/jewelry-box.png",
          price: 300,
          seller: "Love Love",
          colors: [
            Colors.pink,
            Colors.orange,
            Colors.redAccent,
          ],
          category: 4,
          review: "(100 Reviews)",
          rate: 5.0,
          quantity: 1,
        ),
        Product_local(
          id: 23,
          title: "Wedding Ring",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/jewelry/wedding ring.png",
          price: 155,
          seller: "I Am Seller",
          colors: [
            Colors.brown,
            Colors.purpleAccent,
            Colors.blueGrey,
          ],
          category: 4,
          review: "(80 Reviews)",
          rate: 4.5,
          quantity: 1,
        ),
        Product_local(
          id: 24,
          title: "Necklace-Jewellery",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/jewelry/necklace-jewellery.png",
          price: 5000,
          seller: "Jewellery Store",
          colors: [
            Colors.blueAccent,
            Colors.orange,
            Colors.green,
          ],
          category: 4,
          review: "(22 Reviews)",
          rate: 3.5,
          quantity: 1,
        ),
        Product_local(
          id: 25,
          title: "Man Jacket",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/men fashion/man jacket.png",
          price: 500,
          seller: "Men Store",
          colors: [
            Colors.brown,
            Colors.orange,
            Colors.blueGrey,
          ],
          category: 5,
          review: "(90 Reviews)",
          rate: 5.0,
          quantity: 1,
        ),
        Product_local(
          id: 26,
          title: "Men Pants",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/men fashion/pants.png",
          price: 400,
          seller: "My Store",
          colors: [
            Colors.black54,
            Colors.orange,
            Colors.green,
          ],
          category: 5,
          review: "(500 Reviews)",
          rate: 4.5,
          quantity: 1,
        ),
        Product_local(
          id: 27,
          title: "Men Shert",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/men fashion/shert.png",
          price: 300,
          seller: "Roman Store",
          colors: [
            Colors.pink,
            Colors.amber,
            Colors.green,
          ],
          category: 5,
          review: "(200 Reviews)",
          rate: 3.0,
          quantity: 1,
        ),
        Product_local(
          id: 28,
          title: "T-Shirt",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/men fashion/t-shirt.png",
          price: 200,
          seller: "Hot Store",
          colors: [
            Colors.brown,
            Colors.orange,
            Colors.blue,
          ],
          category: 7,
          review: "(1k Reviews)",
          rate: 5.0,
          quantity: 1,
        ),
      ];
    }else{
      return [
        Product_local(
          id: 1,
          title: "Wireless Headphones",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/all/wireless.png",
          price: 120,
          seller: "Tariqul isalm",
          colors: [
            Colors.black,
            Colors.blue,
            Colors.orange,
          ],
          category: 6,
          review: "(320 Reviews)",
          rate: 4.8,
          quantity: 1,
        ),
        Product_local(
          id: 2,
          title: "Woman Sweter",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/all/sweet.png",
          price: 120,
          seller: "Joy Store",
          colors: [
            Colors.brown,
            Colors.deepPurple,
            Colors.pink,
          ],
          category: 7,
          review: "(32 Reviews)",
          rate: 4.5,
          quantity: 1,
        ),
        Product_local(
          id: 3,
          title: "Smart Watch",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/all/miband.jpg",
          price: 55,
          seller: "Ram Das",
          colors: [
            Colors.black,
            Colors.amber,
            Colors.purple,
          ],
          category: 6,
          review: "(20 Reviews)",
          rate: 4.0,
          quantity: 1,
        ),
        Product_local(
          id: 4,
          title: "Mens Jacket",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/all/jacket.png",
          price: 155,
          seller: "Jacket Store",
          colors: [
            Colors.blueAccent,
            Colors.orange,
            Colors.green,
          ],
          category: 5,
          review: "(20 Reviews)",
          rate: 5.0,
          quantity: 1,
        ),
        Product_local(
          id: 5,
          title: "Watch",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/men fashion/watch.png",
          price: 1000,
          seller: "Jacket Store",
          colors: [
            Colors.lightBlue,
            Colors.orange,
            Colors.purple,
          ],
          category: 6,
          review: "(100 Reviews)",
          rate: 5.0,
          quantity: 1,
        ),
        Product_local(
          id: 6,
          title: "Air Jordan",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/shoes/Air Jordan.png",
          price: 255,
          seller: "The Seller",
          colors: [
            Colors.grey,
            Colors.amber,
            Colors.purple,
          ],
          category: 2,
          review: "(55 Reviews)",
          rate: 5.0,
          quantity: 1,
        ),
        Product_local(
          id: 7,
          title: "Super Perfume",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/beauty/perfume.png",
          price: 155,
          seller: "Love Seller",
          colors: [
            Colors.purpleAccent,
            Colors.pinkAccent,
            Colors.green,
          ],
          category: 3,
          review: "(99 Reviews)",
          rate: 4.7,
          quantity: 1,
        ),
        Product_local(
          id: 8,
          title: "Wedding Ring",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/jewelry/wedding ring.png",
          price: 155,
          seller: "I Am Seller",
          colors: [
            Colors.brown,
            Colors.purpleAccent,
            Colors.blueGrey,
          ],
          category: 4,
          review: "(80 Reviews)",
          rate: 4.5,
          quantity: 1,
        ),
        Product_local(
          id:9,
          title: "  Pants",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/women fashion/pants.png",
          price: 155,
          seller: "PK Store",
          colors: [
            Colors.lightGreen,
            Colors.blueGrey,
            Colors.deepPurple,
          ],
          category: 7,
          review: "(55 Reviews)",
          rate: 5.0,
          quantity: 1,
        ),
        Product_local(
          id: 10,
          title: "Air Jordan",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/shoes/Air Jordan.png",
          price: 255,
          seller: "The Seller",
          colors: [
            Colors.grey,
            Colors.amber,
            Colors.purple,
          ],
          category: 2,
          review: "(55 Reviews)",
          rate: 5.0,
          quantity: 1,
        ),
        Product_local(
          id: 11,
          title: "Vans Old Skool",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/shoes/vans old skool.png",
          price: 300,
          seller: "Mrs Store",
          colors: [
            Colors.blueAccent,
            Colors.blueGrey,
            Colors.green,
          ],
          category: 2,
          review: "(200 Reviews)",
          rate: 5.0,
          quantity: 1,
        ),
        Product_local(
          id: 12,
          title: "Women-Shoes",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/shoes/women-shoes.png",
          price: 500,
          seller: "Shoes Store",
          colors: [
            Colors.red,
            Colors.orange,
            Colors.greenAccent,
          ],
          category: 2,
          review: "(100 Reviews)",
          rate: 4.8,
          quantity: 1,
        ),
        Product_local(
          id: 13,
          title: "Sports Shoes",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/shoes/sports shoes.png",
          price: 155,
          seller: "Hari Store",
          colors: [
            Colors.deepPurpleAccent,
            Colors.orange,
            Colors.green,
          ],
          category: 2,
          review: "(60 Reviews)",
          rate: 3.0,
          quantity: 1,
        ),
        Product_local(
          id: 14,
          title: "White Sneaker",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/shoes/white sneaker.png",
          price: 1000,
          seller: "Jacket Store",
          colors: [
            Colors.blueAccent,
            Colors.orange,
            Colors.green,
          ],
          category: 2,
          review: "(00 Reviews)",
          rate: 0.0,
          quantity: 1,
        ),
        Product_local(
          id: 15,
          title: "Face Care Product",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/beauty/face care.png",
          price: 1500,
          seller: "Yojana Seller",
          colors: [
            Colors.pink,
            Colors.amber,
            Colors.deepOrangeAccent,
          ],
          category: 3,
          review: "(200 Reviews)",
          rate: 4.0,
          quantity: 1,
        ),
        Product_local(
          id: 16,
          title: "Super Perfume",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/beauty/perfume.png",
          price: 155,
          seller: "Love Seller",
          colors: [
            Colors.purpleAccent,
            Colors.pinkAccent,
            Colors.green,
          ],
          category: 3,
          review: "(99 Reviews)",
          rate: 4.7,
          quantity: 1,
        ),
        Product_local(
          id: 17,
          title: " Women Kurta",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/women fashion/kurta.png",
          price: 299,
          seller: "Sila Store",
          colors: [
            Colors.grey,
            Colors.black54,
            Colors.purple,
          ],
          category: 7,
          review: "(25 Reviews)",
          rate: 5.0,
          quantity: 1,
        ),
        Product_local(
          id: 18,
          title: "Mens Jacket",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/women fashion/lehenga.png",
          price: 666,
          seller: "My Store",
          colors: [
            Colors.black,
            Colors.orange,
            Colors.green,
          ],
          category: 7,
          review: "(100 Reviews)",
          rate: 4.0,
          quantity: 1,
        ),
        Product_local(
          id: 19,
          title: "T-Shert",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/women fashion/t-shert.png",
          price: 155,
          seller: "Love Store",
          colors: [
            Colors.blueAccent,
            Colors.redAccent,
            Colors.deepOrangeAccent,
          ],
          category: 7,
          review: "(20 Reviews)",
          rate: 5.0,
          quantity: 1,
        ),
        Product_local(
          id: 20,
          title: "  Pants",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/women fashion/pants.png",
          price: 155,
          seller: "PK Store",
          colors: [
            Colors.lightGreen,
            Colors.blueGrey,
            Colors.deepPurple,
          ],
          category: 7,
          review: "(55 Reviews)",
          rate: 5.0,
          quantity: 1,
        ),
        Product_local(
          id: 21,
          title: "Earrings",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/jewelry/earrings.png",
          price: 3000,
          seller: "Gold Store",
          colors: [
            Colors.amber,
            Colors.deepPurple,
            Colors.pink,
          ],
          category: 4,
          review: "(320 Reviews)",
          rate: 4.5,
          quantity: 1,
        ),
        Product_local(
          id: 22,
          title: "Jewelry-Box",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/jewelry/jewelry-box.png",
          price: 300,
          seller: "Love Love",
          colors: [
            Colors.pink,
            Colors.orange,
            Colors.redAccent,
          ],
          category: 4,
          review: "(100 Reviews)",
          rate: 5.0,
          quantity: 1,
        ),
        Product_local(
          id: 23,
          title: "Wedding Ring",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/jewelry/wedding ring.png",
          price: 155,
          seller: "I Am Seller",
          colors: [
            Colors.brown,
            Colors.purpleAccent,
            Colors.blueGrey,
          ],
          category: 4,
          review: "(80 Reviews)",
          rate: 4.5,
          quantity: 1,
        ),
        Product_local(
          id: 24,
          title: "Necklace-Jewellery",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/jewelry/necklace-jewellery.png",
          price: 5000,
          seller: "Jewellery Store",
          colors: [
            Colors.blueAccent,
            Colors.orange,
            Colors.green,
          ],
          category: 4,
          review: "(22 Reviews)",
          rate: 3.5,
          quantity: 1,
        ),
        Product_local(
          id: 25,
          title: "Man Jacket",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/men fashion/man jacket.png",
          price: 500,
          seller: "Men Store",
          colors: [
            Colors.brown,
            Colors.orange,
            Colors.blueGrey,
          ],
          category: 5,
          review: "(90 Reviews)",
          rate: 5.0,
          quantity: 1,
        ),
        Product_local(
          id: 26,
          title: "Men Pants",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/men fashion/pants.png",
          price: 400,
          seller: "My Store",
          colors: [
            Colors.black54,
            Colors.orange,
            Colors.green,
          ],
          category: 5,
          review: "(500 Reviews)",
          rate: 4.5,
          quantity: 1,
        ),
        Product_local(
          id: 27,
          title: "Men Shert",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/men fashion/shert.png",
          price: 300,
          seller: "Roman Store",
          colors: [
            Colors.pink,
            Colors.amber,
            Colors.green,
          ],
          category: 5,
          review: "(200 Reviews)",
          rate: 3.0,
          quantity: 1,
        ),
        Product_local(
          id: 28,
          title: "T-Shirt",
          description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec massa sapien faucibus et molestie ac feugiat. In massa tempor nec feugiat nisl. Libero id faucibus nisl tincidunt.",
          image: "images/men fashion/t-shirt.png",
          price: 200,
          seller: "Hot Store",
          colors: [
            Colors.brown,
            Colors.orange,
            Colors.blue,
          ],
          category: 7,
          review: "(1k Reviews)",
          rate: 5.0,
          quantity: 1,
        ),
      ].where((product) => product.category == categoryId).toList();
    }
  }
}